help:
	@grep '####' Makefile | grep -v grep | sed -e 's/####//'

cart: #### setup Cart component
	@bash components/cart.sh

catalogue: #### setup Catalogue component
	@bash components/catalogue.sh

user: #### setup User component
	@bash components/user.sh

shipping: #### setup Shipping component
	@bash components/shipping.sh

payment: #### setup Payment component
	@bash components/payment.sh

frontend: #### setup Frontend component
	@bash components/frontend.sh

mysql: #### setup Mysql component
	@bash components/mysql.sh

redis: #### setup Redis component
	@bash components/redis.sh

rabbitmq: #### setup RabbitMQ component
	@bash components/cart.sh

mongodb: #### setup MongoDB component
	@bash components/mongodb.sh